const Province = require('../models/ProvinceModel')
const District = require('../models/DistrictModel')

const provinces = [
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "TP. Hồ Chí Minh",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
];

const district = [
    [
        "Tp Long Xuyên",
        "Tp Châu Đốc",
        "Tx Tân Châu",
        "An Phú",
        "Châu Phú",
        "Châu Thành",
        "Chợ Mới",
        "Phú Tân",
        "Thoại Sơn",
        "Tịnh Biên",
        "Tri Tôn"
    ],
    [
        "Tp Vũng Tàu",
        "Tp Bà Rịa",
        "Tx Phú Mỹ",
        "Châu Đức",
        "Xuyên Mộc",
        "Long Điền",
        "Đất Đỏ",
        "Côn Đảo"
    ],
    [
        "Tp Bắc Giang",
        "Lạng Giang",
        "Sơn Động",
        "Tân Yên",
        "Việt Yên",
        "Yên Dũng",
        "Hiệp Hòa",
        "Lục Nam",
        "Lục Ngạn",
        "Yên Thế"
    ],
    [
        "Tp Bắc Kạn",
        "Ba Bể",
        "Bạch Thông",
        "Chợ Đồn",
        "Chợ Mới",
        "Na Rì",
        "Ngân Sơn",
        "Pác Nặm"
    ],
    [
        "Tp Bạc Liêu",
        "Tx Giá Rai",
        "Hòa Binh",
        "Vĩnh Lợi",
        "Hồng Dân",
        "Đông Hải",
        "Phước Long"
    ],
    [
        "Tp Bắc Ninh",
        "Tp Từ Sơn",
        "Thuận Thành",
        "Gia Bình",
        "Lương Tài",
        "Quế Võ",
        "Tiên Du",
        "Yên Phong"
    ],
    [
        "Tp Bến Tre",
        "Châu Thành",
        "Bình Đại",
        "Ba Tri",
        "Chợ Lách",
        "Giồng Trôm",
        "Mỏ Cày Bắc",
        "Mỏ Cày Nam",
        "Thạnh Phú"
    ],
    [
        "Tp Quy Nhơn",
        "Tx An Nhơn",
        "Tx Hoài Nhơn",
        "Phù Mỹ",
        "Tuy Phước",
        "Vân Canh",
        "Tây Sơn",
        "An Lão",
        "Hoài Ân",
        "Phù Cát",
        "Vĩnh Thạnh"
    ],
    [
        "Tp Thủ Dầu Một",
        "Tp Dĩ An",
        "Tp Thuận An",
        "Tx Bến Cát",
        "Tx Tân Uyên",
        "Dầu Tiếng",
        "Bàu Bàng",
        "Phú Giáo",
        "Bắc Tân Uyên"
    ],
    [
        "Tp Đồng Xoài",
        "Tx Bình Long",
        "Tx Phước Long",
        "Bù Đốp",
        "Đồng Phú",
        "Bù Đăng",
        "Bù Gia Mập",
        "Chơn Thành",
        "Hớn Quản",
        "Lộc Ninh",
        "Phú Riềng"
    ],
    [
        "Tp Phan Thiết",
        "Tx La Gi",
        "Bắc Bình",
        "Đức Linh",
        "Hàm Tân",
        "Hàm Thuận Bắc",
        "Hàm Thuận Nam",
        "Phú Quý",
        "Tánh Linh",
        "Tuy Phong"
    ],
    [
        "Tp Cà Mau",
        "Ngọc Hiển",
        "Cái Nước",
        "Đầm Dơi",
        "Năm Căn",
        "Phú Tân",
        "Thới Bình",
        "Trần Văn Thời",
        "U Minh",
    ],
    [
        "Quận Ninh Kiều",
        "Quận Bình Thủy",
        "Quận Cái Răng",
        "Quận Ô Môn",
        "Quận Thốt Nốt",
        "Phong Điền",
        "Cờ Đỏ",
        "Vĩnh Thạnh",
        "Thới Lai"
    ],
    [
        "Tp Cao Bằng",
        "Bảo Lâm",
        "Bảo Lạc",
        "Hạ Lang",
        "Hà Quảng",
        "Hòa An",
        "Nguyên Bình",
        "Thạch An",
        "Trùng Khánh",
        "Quảng Hòa"
    ],
    [
        "Quận Hải Châu",
        "Quận Thanh Khê",
        "Quận Liên Chiểu",
        "Quận Ngũ Hành Sơn",
        "Quận Sơn Trà",
        "Quận Cẩm Lệ",
        "Hòa Vang",

    ],
    [
        "Tp Buôn Ma Thuột",
        "Tp Buôn Hồ",
        "Buôn Đôn",
        "Cư Kuin",
        "Cư M'gar",
        "Ea H'leo",
        "Ea Kar",
        "Ea Súp",
        "Krông Ana",
        "Krông Bông",
        "Krông Búk",
        "Krông Năng",
        "Krông Pắc",
        "Lắk",
        "M'Đrắk"
    ],
    [
        "Tp Gia Nghĩa",
        "Cư Jút",
        "Đắk Glong",
        "Đắk Mil",
        "Đắk R'Lấp",
        "Đắk Song",
        "Krông Nô",
        "Tuy Đức"
    ],
    [
        "Tp Điện Biên Phủ",
        "Tx Mường Lay",
        "Điện Biên",
        "Mường Ảng",
        "Mường Chà",
        "Mường Nhé",
        "Tuần Giáo",
        "Tủa Chùa",
        "Điện Biên Đông",
    ],
    [
        "Tp Biên Hòa",
        "Tp Long Khánh",
        "Cẩm Mỹ",
        "Định Quán",
        "Long Thành",
        "Nhơn Trạch",
        "Tân Phú",
        "Thống Nhất",
        "Trảng Bom",
        "Vĩnh Cửu",
        "Xuân Lộc"
    ],
    [
        "Tp Cao Lãnh",
        "Tp Hồng Ngự",
        "Tp Đa Séc",
        "Cao Lãnh",
        "Châu Thành",
        "Hồng Ngự",
        "Lai Vung",
        "Lấp Vò",
        "Tam Nông",
        "Tân Hồng",
        "Thanh Bình",
        "Tháp Mười"
    ],
    [
        "Tp Pleiku",
        "Tx An Khê",
        "Tx Ayun Pa",
        "Chư Păh",
        "Chư Prông",
        "Chư Pưh",
        "Chư Sê",
        "Đắk Đoa",
        "Đăk Pơ",
        "Đức Cơ",
        "Ia Grai",
        "Ia Pa",
        "K'Bang",
        "Kông Chro",
        "Krông Pa",
        "Mang Yang",
        "Phú Thiện"
    ],
    [
        "Tp Hà Giang",
        "Mèo Vạc",
        "Đồng Văn",
        "Mèo Vạc",
        "Bắc Mê",
        "Bắc Quang",
        "Quản Bạ",
        "Quang Bình",
        "Vị Xuyên",
        "Xín Mần",
        "Yên Minh"
    ],
    [
        "Tp Phủ Lý",
        "Tx Duy Tiên",
        "Bình Lục",
        "Kim Bảng",
        "Lý Nhân",
        "Thanh Liêm"
    ],
    [
        "Ba Đình",
        "Hoàn Kiếm",
        "Hai Bà Trưng",
        "Đống Đa",
        "Tây Hồ",
        "Cầu Giấy",
        "Thanh Xuân",
        "Hoàng Mai",
        "Long Biên",
        "Nam Từ Liêm",
        "Bắc Từ Liêm",
        "Hà Đông",
        "Mỹ Đình",
        "Sóc Sơn",
        "Đông Anh",
        "Gia Lâm",
        "Thanh Trì",
        "Hoài Đức",
        "Thường Tín",
        "Phú Xuyên",
        "Mê Linh",
        "Đan Phượng",
        "Chương Mỹ",
        "Thanh Oai",
        "Ứng Hòa",
        "Mỹ Đức",
        "Ba Vì",
        "Phúc Thọ",
        "Quốc Oai",
        "TX Sơn Tây"
    ],
    [
        "Tp Hà Tĩnh",
        "Tx Hồng Lĩnh",
        "Tx Kỳ Anh",
        "Cẩm Xuyên",
        "Can Lộc",
        "Đức Thọ",
        "Hương Khê",
        "Hương Sơn",
        "Lộc Hà",
        "Nghi Xuân",
        "Thạch Hà",
        "Vũ Quang",
    ],
    [
        "Tp Hải Dương",
        "Tp Chí Linh",
        "Tx Kinh Môn",
        "Bình Giang",
        "Cẩm Giàng",
        "Gia Lộc",
        "Kim Thành",
        "Nam Sách",
        "Ninh Giang",
        "Thanh Hà",
        "Thanh Miện",
        "Tứ Kỳ"
    ],
    [
        "Đồ Sơn",
        "Dương Kinh",
        "Hồng Bàng",
        "Ngô Quyền",
        "Lê Chân",
        "Hải An",
        "Kiến An",
        "An Dương",
        "An Lão",
        "Kiến Thụy",
        "Thủy Nguyên",
        "Tiên Lãng",
        "Vĩnh Bảo",
        "Cát Hải",
        "Bạch Long Vĩ"
    ],
    [
        "Tp Vị Thanh",
        "Tp Ngã Bảy",
        "Tx Long Mỹ",
        "Châu Thành",
        "Châu Thành A",
        "Phụng Hiệp",
        "Vị Thủy"
    ],
    [
        "Tp Hòa Bình",
        "Mai Châu",
        "Cao Phong",
        "Đà Bắc",
        "Kim Bôi",
        "Lạc Sơn",
        "Lạc Thủy",
        "Lương Sơn",
        "Tân Lạc",
        "Yên Thủy"
    ],
    [
        "Tp Hưng Yên",
        "Tx Mỹ Hào",
        "Ân Thi",
        "Khoái Châu",
        "Kim Động",
        "Phù Cừ",
        "Tiên Lữ",
        "Văn Giang",
        "Văn Lâm",
        "Yên Mỹ"
    ],
    [
        "Tp Nha Trang",
        "Tp Cam Ranh",
        "Tx Ninh Hòa",
        "Cam Lâm",
        "Diên Khánh",
        "Khánh Sơn",
        "Khánh Vĩnh",
        "Trường Sa",
        "Vạn Ninh"
    ],
    [
        "Tp Rạch Giá",
        "Tp Hà Tiên",
        "Tp Phú Quốc",
        "Kiên Lương",
        "Hòn Đất",
        "Tân Hiệp",
        "Giồng Riềng",
        "Gò Quao",
        "An Biên",
        "An Minh",
        "Châu Thành",
        "Giang Thành",
        "Kiên Hải",
        "U Minh Thượng",
        "Vĩnh Thuận"
    ],
    [
        "Tp Kon Tum",
        "Đắk Glei",
        "Đắk Hà",
        "Đắk Tô",
        "Kon Plông",
        "Kon Rẫy",
        "Ngọc Hồi",
        "Sa Thầy",
        "Tu Mơ Rông"
    ],
    [
        "Tp Lai Châu",
        "Mường Tè",
        "Nậm Nhùn",
        "Phong Thổ",
        "Sìn Hồ",
        "Tam Đường",
        "Tân Uyên",
        "Than Uyên"
    ],
    [
        "Tp Đà Lạt",
        "Tp Bảo Lộc",
        "Bảo Lâm",
        "Cát Tiên",
        "Đạ Huoai",
        "Đạ Tẻh",
        "Đam Rông",
        "Di Linh",
        "Đơn Dương",
        "Đức Trọng",
        "Lạc Dương",
        "Lâm Hà"
    ],
    [
        "Tp Lạng Sơn",
        "Bắc Sơn",
        "Bình Gia",
        "Cao Lộc",
        "Chi Lăng",
        "Đình Lập",
        "Hữu Lũng",
        "Lộc Bình",
        "Tràng Định",
        "Văn Lãng",
        "Văn Quan"
    ],
    [
        "Tp Lào Cai",
        "Tx Sa Pa",
        "Bắc Hà",
        "Bảo Thắng",
        "Bảo Yên",
        "Bát Xát",
        "Mường Khương",
        "Si Ma Cai",
        "Văn Bàn"
    ],
    [
        "Tp Tân An",
        "Tx Kiến Tường",
        "Bến Lức",
        "Cần Đước",
        "Cần Giuộc",
        "Châu Thành",
        "Đức Hòa",
        "Đức Huệ",
        "Mộc Hóa",
        "Tân Hưng",
        "Tân Thạnh",
        "Tân Trụ",
        "Thạnh Hóa",
        "Thủ Thừa",
        "Vĩnh Hưng"
    ],
    [
        "Tp Nam Định",
        "Vụ Bản",
        "Giao Thủy",
        "Hải Hậu",
        "Mỹ Lộc",
        "Nam Trực",
        "Trực Ninh",
        "Xuân Trường",
        "Ý Yên",
        "Nghĩa Hưng"
    ],
    [
        "Tp Vinh",
        "Tx Cửa Lò",
        "Tx Thái Hòa",
        "Tx Hoàng Mai",
        "Anh Sơn",
        "Con Cuông",
        "Diễn Châu",
        "Đô Lương",
        "Hưng Nguyên",
        "Kỳ Sơn",
        "Nam Đàn",
        "Nghi Lộc",
        "Nghĩa Đàn",
        "Quế Phong",
        "Quỳ Châu",
        "Quỳ Hợp",
        "Quỳnh Lưu",
        "Tân Kỳ",
        "Thanh Chương",
        "Tương Dương",
        "Yên Thành"
    ],
    [
        "Tp Ninh Bình",
        "Tp Tam Điệp",
        "Gia Viễn",
        "Hoa Lư",
        "Kim Sơn",
        "Nho Quan",
        "Yên Khánh",
        "Yên Mô"
    ],
    [
        "Tp Phan Rang-Tháp Chàm",
        "Bác Ái",
        "Ninh Hải",
        "Ninh Phước",
        "Ninh Sơn",
        "Thuận Bắc",
        "Thuận Nam"
    ],
    [
        "Tp Việt Trì",
        "Tx Phú Thọ",
        "Cẩm Khê",
        "Đoan Hùng",
        "Hạ Hòa",
        "Lâm Thao",
        "Phù Ninh",
        "Tam Nông",
        "Tân Sơn",
        "Thanh Ba",
        "Thanh Sơn",
        "Thanh Thủy",
        "Yên Lập"
    ],
    [
        "Tp Tuy Hòa",
        "Tx Đông Hòa",
        "Tx Sông Cầu",
        "Đồng Xuân",
        "Phú Hòa",
        "Sông Hinh",
        "Tây Hòa",
        "Tuy An"
    ],
    [
        "Tp Đồng Hới",
        "Tx Ba Đồn",
        "Bố Trạch",
        "Lệ Thủy",
        "Minh Hóa",
        "Quảng Ninh",
        "Quảng Trạch",
        "Tuyên Hóa"
    ],
    [
        "Tp Tam Kỳ",
        "Tp Hội An",
        "Tx Điện Bàn",
        "Bắc Trà My",
        "Đại Lộc",
        "Đông Giang",
        "Duy Xuyên",
        "Hiệp Đức",
        "Nam Giang",
        "Nam Trà My",
        "Nông Sơn",
        "Núi Thành",
        "Phú Ninh",
        "Phước Sơn",
        "Quế Sơn",
        "Tây Giang",
        "Thăng Bình",
        "Tiên Phước"
    ],
    [
        "Tp Quảng Ngãi",
        "Tx Đức Phổ",
        "Ba Tơ",
        "Bình Sơn",
        "Lý Sơn",
        "Minh Long",
        "Mộ Đức",
        "Nghĩa Hành",
        "Sơn Hà",
        "Sơn Tây",
        "Sơn Tịnh",
        "Trà Bồng",
        "Tư Nghĩa"
    ],
    [
        "Tp Hạ Long",
        "Tp Móng Cái",
        "Tp Cẩm phả",
        "Tp Uông Bí",
        "Tx Đông Triều",
        "Tx Quảng Yên",
        "Ba Chẽ",
        "Bình Liêu",
        "Cô Tô",
        "Đầm Hà",
        "Hải Hà",
        "Tiên Yên",
        "Vân Đồn"
    ],
    [
        "Tp Đông Hà",
        "Tx Quảng Trị",
        "Cam Lộ",
        "Cồn Cỏ",
        "Đa Krông",
        "Gio Linh",
        "Hải Lăng",
        "Hướng Hóa",
        "Triệu Phong",
        "Vĩnh Linh"
    ],
    [
        "Tp Sóc Trăng",
        "Tx Ngã Năm",
        "Tx Vĩnh Châu",
        "Châu Thành",
        "Cù Lao Dung",
        "Kế Sách",
        "Long Phú",
        "Mỹ Tú",
        "Mỹ Xuyên",
        "Thạnh Trị",
        "Trần Đề"
    ],
    [
        "Tp Sơn La",
        "Sông Mã",
        "Mường La",
        "Quỳnh Nhai",
        "Thuận Châu",
        "Bắc Yên",
        "Mai Sơn",
        "Phù Yên",
        "Mộc Châu",
        "Yên Châu",
        "Vân Hồ",
        "Sốp Cộp"
    ],
    [
        "Tp Tây Ninh",
        "Tx Trảng Bàng",
        "Tx Hòa Thành",
        "Tân Châu",
        "Gò Dầu",
        "Bến Cầu",
        "Tân Biên",
        "Dương Minh Châu",
        "Châu Thành"
    ],
    [
        "Tp Thái Bình",
        "Thái Thụy",
        "Quỳnh Phụ",
        "Hưng Hà",
        "Đông Hưng",
        "Tiền Hải",
        "Kiến Xương",
        "Vũ Thư"
    ],
    [
        "Tp Phổ Yên",
        "Tp Thái Nguyên",
        "Tp Sông Công",
        "Định Hóa",
        "Phú Lương",
        "Đồng Hỷ",
        "Võ Nhai",
        "Đại Từ",
        "Phú Bình"
    ],
    [
        "Tp Thanh Hóa",
        "Tp Bỉm Sơn",
        "Tx Sầm Sơn",
        "Tx Nghi Sơn",
        "Bá Thước",
        "Cẩm Thủy",
        "Ngọc Lặc",
        "Hậu Lộc",
        "Nga Sơn",
        "Quảng Xương",
        "Thọ Xuân",
        "Thiệu Hóa",
        "Triệu Sơn",
        "Yên Định",
        "Hòa Lộc",
        "Tĩnh Gia",
        "Thường Xuân",
        "Quan Hóa",
        "Nông Cống",
        "Như Xuân",
        "Lang Chánh",
        "Hoằng Hóa",
        "Đông Sơn",
        "Hà Trung",
    ],
    [
        "Tp Huế",
        "Tx Hương Thủy",
        "Tx Hương Trà",
        "A Lưới",
        "Nam Đông",
        "Phong Điền",
        "Phú Lộc",
        "Phú Vang",
        "Quảng Điền"
    ],
    [
        "Tp Mỹ Tho",
        "Tx Gò Công",
        "Tx Cai Lậy",
        "Cái Bè",
        "Châu Thành",
        "Cờ Đỏ",
        "Gò Công Đông",
        "Gò Công Tây",
        "Tân Phước",
        "Tân Phú Đông",
        "Chợ Gạo"
    ],
    [
        "Quận 1",
        "Quận 3",
        "Quận 4",
        "Quận 5",
        "Quận 6",
        "Quận 7",
        "Quận 8",
        "Quận 10",
        "Quận 11",
        "Quận 12",
        "Quận Bình Tân",
        "Quận Bình Thạnh",
        "Quận Gò Vấp",
        "Quận Phú Nhuận",
        "Quận Tân Bình",
        "Quận Tân Phú",
        "Tp Thủ Đức",
        "Bình Chánh",
        "Cần Giờ",
        "Củ Chi",
        "Hóc Môn",
        "Nhà Bè"
    ],
    [
        "Tp Trà Vinh",
        "Tx Duyên Hải",
        "Càng Long",
        "Cầu Kè",
        "Tiểu Cần",
        "Châu Thành",
        "Cầu Ngang",
        "Trà Cú",
        "Duyên Hải"
    ],
    [
        "Tp Tuyên Quang",
        "Sơn Dương",
        "Chiêm Hóa",
        "Hàm Yên",
        "Lâm Bình",
        "Na Hang",
        "Yên Sơn"
    ],
    [
        "Tp Vĩnh Long",
        "Tx Bình Minh",
        "Bình Tân",
        "Long Hồ",
        "Mang Thít",
        "Tam Bình",
        "Trà Ôn",
        "Vũng Liêm"
    ],
    [
        "Tp Vĩnh Yên",
        "Tp Phúc Yên",
        "Bình Xuyên",
        "Lập Thạch",
        "Sông Lô",
        "Tam Dương",
        "Tam Đảo",
        "Vĩnh Tường",
        "Yên Lạc"
    ],
    [
        "Tp Yên Bái",
        "Tx Nghĩa Lộ",
        "Lục Yên",
        "Mù Cang Chải",
        "Trạm Tấu",
        "Trấn Yên",
        "Văn Chấn",
        "Văn Yên",
        "Yên Bình"
    ]

]
const addPlace = (id) => {
    return new Promise(async (resolve, reject) => {
        try {

            let id = 0;
            for (let i = 0; i < provinces.length; i++) {
                for (let j = 0; j < district[i].length; j++) {
                    await District.create({
                        _id: id + 1,
                        provinceId: i + 1,
                        name: district[i][j]
                    })
                    id++;
                }

            }

            // for (let i = 0; i < provinces.length; i++) {
            //     await Province.create({
            //         _id: i + 1,
            //         name: provinces[i]
            //     })
            // }
            resolve({
                status: 'OK',
                message: 'adđ',
            })
        } catch (e) {
            reject(e)
        }
    })
}

const getAllProvince = () => {
    return new Promise(async (resolve, reject) => {
        try {
            const listProvince = await Province.find()
            resolve({
                status: 'OK',
                message: 'Lấy danh sách tỉnh thành công!',
                data: listProvince
            })
        } catch (e) {
            reject(e)
        }
    })
}

const getDistrictByProvince = (provinceId) => {
    return new Promise(async (resolve, reject) => {
        try {
            const listDistrict = await District.find({ provinceId: provinceId })
            resolve({
                status: 'OK',
                message: 'Lấy danh sách huyện thành công!',
                data: listDistrict
            })
        } catch (e) {
            reject(e)
        }
    })
}

module.exports = {
    addPlace,
    getAllProvince,
    getDistrictByProvince
}